[package]
name = "riff-ani"
description = "Generating the animated mouse cursor files (.ani) for Windows."
license = "MPL-2.0"
version = "0.1.0"
authors = ["Balthild <ibalthild@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.22"
riff = "1.0.1"
ico = "0.1.0"
byteorder = "1.3.4"
